package hr.apartmentmanager.web.model;


import java.time.LocalDate;
import java.util.HashMap;
import java.util.HashSet;
import java.util.Map;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Transient;

import org.springframework.beans.factory.annotation.Autowired;

/**
 * Apartment generated by hbm2java
 */
@Entity
@Table(name="apartment")
public class Apartment implements java.io.Serializable {

	@Id
	@GeneratedValue(strategy=GenerationType.IDENTITY)
	@Column(name="apartmentId")
	private Integer apartmentId;
	private Integer baseCapacity;
	private Integer additionalCapacity;
	private String apartmentName;
	private String internalName;
	private String apartmentNote;
	@OneToMany(targetEntity=PricePerNight.class, mappedBy="apartment", fetch=FetchType.EAGER)
	private Set pricepernights = new HashSet(0);
	@OneToMany(targetEntity=Reservation.class, mappedBy="apartment", fetch=FetchType.LAZY)
	private Set<Reservation> reservations = new HashSet<Reservation>(0);
	@Transient
	@Autowired
	private Map<LocalDate, Reservation> apartmentReservations = new HashMap<LocalDate, Reservation>();

	public Apartment() {
	}

	public Apartment(Integer baseCapacity, Integer additionalCapacity, String apartmentName, String internalName,
			String apartmentNote, Set pricepernights) {
		this.baseCapacity = baseCapacity;
		this.additionalCapacity = additionalCapacity;
		this.apartmentName = apartmentName;
		this.internalName = internalName;
		this.apartmentNote = apartmentNote;
		this.pricepernights = pricepernights;
	}

	public Integer getApartmentId() {
		return this.apartmentId;
	}

	public void setApartmentId(Integer apartmentId) {
		this.apartmentId = apartmentId;
	}

	public Integer getBaseCapacity() {
		return this.baseCapacity;
	}

	public void setBaseCapacity(Integer baseCapacity) {
		this.baseCapacity = baseCapacity;
	}

	public Integer getAdditionalCapacity() {
		return this.additionalCapacity;
	}

	public void setAdditionalCapacity(Integer additionalCapacity) {
		this.additionalCapacity = additionalCapacity;
	}

	public String getApartmentName() {
		return this.apartmentName;
	}

	public void setApartmentName(String apartmentName) {
		this.apartmentName = apartmentName;
	}

	public String getInternalName() {
		return this.internalName;
	}

	public void setInternalName(String internalName) {
		this.internalName = internalName;
	}

	public String getApartmentNote() {
		return this.apartmentNote;
	}

	public void setApartmentNote(String apartmentNote) {
		this.apartmentNote = apartmentNote;
	}

	public Set getPricepernights() {
		return this.pricepernights;
	}

	public void setPricepernights(Set pricepernights) {
		this.pricepernights = pricepernights;
	}

	public Map<LocalDate, Reservation> getApartmentReservations() {
		return apartmentReservations;
	}
	
	

}
