package hr.apartmentmanager.web.model;

import java.util.Date;

import javax.persistence.Embeddable;

/**
 * PricepernightId generated by hbm2java
 */
@Embeddable
public class PricepernightId implements java.io.Serializable {

	private int apartmentId;
	private Date priceFrom;

	public PricepernightId() {
	}

	public PricepernightId(int apartmentId, Date priceFrom) {
		this.apartmentId = apartmentId;
		this.priceFrom = priceFrom;
	}

	public int getApartmentId() {
		return this.apartmentId;
	}

	public void setApartmentId(int apartmentId) {
		this.apartmentId = apartmentId;
	}

	public Date getPriceFrom() {
		return this.priceFrom;
	}

	public void setPriceFrom(Date priceFrom) {
		this.priceFrom = priceFrom;
	}

	@Override
	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof PricepernightId))
			return false;
		PricepernightId castOther = (PricepernightId) other;

		return (this.getApartmentId() == castOther.getApartmentId())
				&& ((this.getPriceFrom() == castOther.getPriceFrom()) || (this.getPriceFrom() != null
						&& castOther.getPriceFrom() != null && this.getPriceFrom().equals(castOther.getPriceFrom())));
	}

	@Override
	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getApartmentId();
		result = 37 * result + (getPriceFrom() == null ? 0 : this.getPriceFrom().hashCode());
		return result;
	}

}
