package hr.apartmentmanager.web.model;


import java.math.BigDecimal;
import java.util.Date;

import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.MapsId;
import javax.persistence.Table;

/**
 * Pricepernight generated by hbm2java
 */
@Entity
@Table(name="pricePerNight")
public class PricePerNight implements java.io.Serializable {

	@EmbeddedId
	private PricepernightId id;
    
	@ManyToOne
	@JoinColumn(name="apartmentId")
	@MapsId("apartmentId")
	private Apartment apartment;
	private Date priceTo;
	private BigDecimal price;

	public PricePerNight() {
	}

	public PricePerNight(PricepernightId id, Apartment apartment) {
		this.id = id;
		this.apartment = apartment;
	}

	public PricePerNight(PricepernightId id, Apartment apartment, Date priceTo, BigDecimal price) {
		this.id = id;
		this.apartment = apartment;
		this.priceTo = priceTo;
		this.price = price;
	}

	public PricepernightId getId() {
		return this.id;
	}

	public void setId(PricepernightId id) {
		this.id = id;
	}

	
	public Apartment getApartment() {
		return this.apartment;
	}

	public void setApartment(Apartment apartment) {
		this.apartment = apartment;
	}
	

	public Date getPriceTo() {
		return this.priceTo;
	}

	public void setPriceTo(Date priceTo) {
		this.priceTo = priceTo;
	}

	public BigDecimal getPrice() {
		return this.price;
	}

	public void setPrice(BigDecimal price) {
		this.price = price;
	}

}
